project:
  type: website
  output-dir: docs

website:
  title: "VLab5 Course"
  search: true

  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Global Tuna Atlas & VLab5"
        menu:
          - href: lesson-3-1-overview.qmd
            text: "ðŸ“˜ Lesson 3.1 Overview"
          - href: lesson-3-5-overview.qmd
            text: "ðŸŽ“ Lesson 3.2 Overview"

  sidebar:
    - id: module3
      title: "Module 3 â€” Global Tuna Atlas & VLab5"
      style: docked
      collapse-level: 1
      contents:
        - section: "Lesson 3.1 â€” Intro to Global Tuna Atlas (incoming)"
          contents:
            # - lesson-3-1-overview.qmd
            # - gta-datasets-architecture.qmd
            # - gta-dataset-specificities.qmd
            # - gta-standards-fair.qmd
            # - gta-materials.qmd
            # - gta-quiz.qmd
        - section: "Lesson 3.2 â€” Running R Workflows in VLab5"
          contents:
            - lesson-3-5-overview.qmd
            - intro-rstudio.qmd
            - project-organization.qmd
            - running-scripts-in-loaded-repo.qmd
            - renv-cache-path.qmd
            - deploy-repos-in-vlab-rstudioserver.qmd
        - section: "Lesson 3.3 â€” Exploring Global Tuna Atlas data through Shiny applications in the VLab 5"
          contents:
            - exploring-global-tuna-atlas-data-via-shiny.qmd


format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    code-copy: true
    link-external: true
    link-external-icon: true
    smooth-scroll: true
